server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/welt_blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  redis:
    host: 111.111.111.11
    password: 111111

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKeyId: kid
  accessKeySecret: ks
  bucket: bucket

